### ISSUE TITLE
Deploy in Ubuntu 16.04 error

### ISSUE THREAD

**Issue by sicute** [Achain-Dev/Achain#132]
hi ..
i follow this tutorial https://github.com/Achain-Dev/Achain/blob/master/linux_installation_guide
failed at  " 5). install fast compile library"
any clue 

[ 40%] Building CXX object CMakeFiles/fc.dir/src/log/logger.cpp.o
[ 41%] Building CXX object CMakeFiles/fc.dir/src/log/appender.cpp.o
[ 42%] Building CXX object CMakeFiles/fc.dir/src/log/console_appender.cpp.o
[ 42%] Building CXX object CMakeFiles/fc.dir/src/log/file_appender.cpp.o
/home/ubuntu/leveldb-1.20/miniupnpc-1.8.20131209/fast-compile/src/log/file_appender.cpp: In constructor ‘fc::file_appender::file_appender(const fc::variant&)’:
/home/ubuntu/leveldb-1.20/miniupnpc-1.8.20131209/fast-compile/src/log/file_appender.cpp:161:15: error: ‘cerr’ is not a member of ‘std’
          std::cerr << "error opening log file: " << my->cfg.filename.preferred_string() << "\n";
               ^~~~
/home/ubuntu/leveldb-1.20/miniupnpc-1.8.20131209/fast-compile/src/log/file_appender.cpp:161:15: note: suggested alternative: ‘erf’
          std::cerr << "error opening log file: " << my->cfg.filename.preferred_string() << "\n";
               ^~~~
               erf
CMakeFiles/fc.dir/build.make:1022: recipe for target 'CMakeFiles/fc.dir/src/log/file_appender.cpp.o' failed
make[2]: *** [CMakeFiles/fc.dir/src/log/file_appender.cpp.o] Error 1
CMakeFiles/Makefile2:300: recipe for target 'CMakeFiles/fc.dir/all' failed
make[1]: *** [CMakeFiles/fc.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
root@ip-172-31-92-43:/home/ubuntu/leveldb-1.20/miniupnpc-1.8.20131209/fast-compile#

**Comment by owenSai** [comment]
use version  v2.0

**Comment by sicute** [comment]
ok thanks working
