### ISSUE TITLE
how to release a token based on Achain?

### ISSUE THREAD

**Issue by fendouai** [Achain-Dev/Achain#72]
?

**Comment by fendouai** [comment]
Is there a guide like eth.

**Comment by owenSai** [comment]
we can release tokens based on achain via contract like eth, you can contact achain official if you want.

**Comment by fendouai** [comment]
you are not the official?

**Comment by farmerljx** [comment]
Just contact to the official, there have been some tokens based on achain. see www.achain.com and browser.achain.com.
