### ISSUE TITLE
你们的开发进度好慢啊

### ISSUE THREAD

**Issue by longzhixin** [Achain-Dev/Achain#75]
到现在都没有一个全节点的钱包，你们做的是区块链么。。。

**Comment by JackLeeAchain** [comment]
请问你是想问钱包吗？
https://www.achain.com/
这里页面上有下载地址。

**Comment by loktarjugg** [comment]
对开发人员是不友好... 类似以太坊`web3.js`、私有链(开发)部署等等好像都没有啊..
`Glua`文档里强烈推荐的`信和云合约IDE开发工具`在哪里...没有找到，google到一家叫[信和云](http://www.thinkyoung.com.cn/)的网站，打开信和云智能合约平台又是504 好曲折...

对了，桌面版的钱包 `MAC` 版本啥时候发

希望官方提供一个较为完善的开发环境搭建教程...

**Comment by JackLeeAchain** [comment]
感谢反馈。
windows版和MAC版的全节点钱包细节在打磨中。windows版本会陆续更新，mac版会于近期发布。
我们的底层链跟上层应用是通过http-isonrpc方式连接的，具体可以参考https://www.achain.com/help/rpc.html
关于私有链部署我们后面会逐步完善到官网或者github上，敬请关注。
